// Generated by scripts/location-photos/build.py — edit the script, not this file.
// Photos are freely licensed from Wikimedia Commons; credit stays with each photographer.

export interface LocationPhoto {
  slug: string;
  src: string;
  width: number;
  height: number;
  alt: string;
  title: string;
  caption: string;
  lat: number;
  lon: number;
  credit: {
    author: string;
    license: string;
    licenseUrl: string | null;
    sourceUrl: string;
    attributionRequired: boolean;
  };
}

export const LOCATION_PHOTOS: Record<string, LocationPhoto> = {
  "santa-monica": {
    "slug": "santa-monica",
    "src": "/locations/santa-monica-junk-removal-santa-monica-pier.jpg",
    "width": 1600,
    "height": 900,
    "alt": "Santa Monica Pier and Pacific Park Ferris wheel at sunset over the beach in Santa Monica, California",
    "title": "Santa Monica Pier — Junk Removal in Santa Monica, CA | Dump Happy",
    "caption": "Santa Monica Pier, Santa Monica",
    "lat": 34.0086,
    "lon": -118.4986,
    "credit": {
      "author": "CucombreLibre from New York, NY, USA",
      "license": "CC BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Santa_Monica_Pier_(22944807230).jpg",
      "attributionRequired": true
    }
  },
  "culver-city": {
    "slug": "culver-city",
    "src": "/locations/culver-city-junk-removal-culver-hotel.jpg",
    "width": 1600,
    "height": 900,
    "alt": "The historic Culver Hotel lit up at twilight in downtown Culver City, California",
    "title": "The historic Culver Hotel — Junk Removal in Culver City, CA | Dump Happy",
    "caption": "The historic Culver Hotel, Culver City",
    "lat": 34.0232,
    "lon": -118.396,
    "credit": {
      "author": "CulverHotel",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Culver_by_Night_-_Seiichi_Niitsuma.jpg",
      "attributionRequired": true
    }
  },
  "beverly-hills": {
    "slug": "beverly-hills",
    "src": "/locations/beverly-hills-junk-removal-palm-lined-street.jpg",
    "width": 1600,
    "height": 900,
    "alt": "Tall palm trees lining a quiet residential street in Beverly Hills, California",
    "title": "A palm-lined residential street — Junk Removal in Beverly Hills, CA | Dump Happy",
    "caption": "A palm-lined residential street, Beverly Hills",
    "lat": 34.0736,
    "lon": -118.4004,
    "credit": {
      "author": "Adrian104",
      "license": "Public domain",
      "licenseUrl": null,
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Beverly_Hills11.JPG",
      "attributionRequired": false
    }
  },
  "west-hollywood": {
    "slug": "west-hollywood",
    "src": "/locations/west-hollywood-junk-removal-sunset-tower.jpg",
    "width": 1600,
    "height": 900,
    "alt": "Art Deco Sunset Tower above the apartments and tree-lined streets of West Hollywood, California",
    "title": "Sunset Tower on the Sunset Strip — Junk Removal in West Hollywood, CA | Dump Happy",
    "caption": "Sunset Tower on the Sunset Strip, West Hollywood",
    "lat": 34.0957,
    "lon": -118.3747,
    "credit": {
      "author": "MikeJiroch",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sunset_Tower,_8358_Sunset_Blvd._West_Hollywood_2364.jpg",
      "attributionRequired": true
    }
  },
  "marina-del-rey": {
    "slug": "marina-del-rey",
    "src": "/locations/marina-del-rey-junk-removal-harbor.jpg",
    "width": 1600,
    "height": 900,
    "alt": "Boats docked in the Marina del Rey harbor with waterfront condos behind, Marina del Rey, California",
    "title": "The Marina del Rey harbor — Junk Removal in Marina del Rey, CA | Dump Happy",
    "caption": "The Marina del Rey harbor, Marina del Rey",
    "lat": 33.9803,
    "lon": -118.4517,
    "credit": {
      "author": "P. Hughes",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marina_del_Rey.jpg",
      "attributionRequired": true
    }
  },
  "venice": {
    "slug": "venice",
    "src": "/locations/venice-junk-removal-venice-canals.jpg",
    "width": 1600,
    "height": 900,
    "alt": "Homes reflected in the water along the Venice Canal Historic District in Venice, Los Angeles",
    "title": "The Venice Canals — Junk Removal in Venice, CA | Dump Happy",
    "caption": "The Venice Canals, Venice",
    "lat": 33.985,
    "lon": -118.4695,
    "credit": {
      "author": "Américo Toledano",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Los_Angeles_-_Venice_Canal_Historic_District_04.jpg",
      "attributionRequired": true
    }
  },
  "sawtelle": {
    "slug": "sawtelle",
    "src": "/locations/sawtelle-junk-removal-west-los-angeles-streetcar-depot.jpg",
    "width": 1600,
    "height": 900,
    "alt": "Historic West Los Angeles Streetcar Depot under palm and eucalyptus trees on the Sawtelle Veterans Home grounds, Los Angeles",
    "title": "The historic West Los Angeles Streetcar Depot — Junk Removal in Sawtelle, CA | Dump Happy",
    "caption": "The historic West Los Angeles Streetcar Depot, Sawtelle",
    "lat": 34.056,
    "lon": -118.4555,
    "credit": {
      "author": "SBW",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:West_Los_Angeles_Streetcar_Depot_on_the_grounds_of_the_Sawtelle_Veterans_Home.jpg",
      "attributionRequired": true
    }
  },
  "brentwood": {
    "slug": "brentwood",
    "src": "/locations/brentwood-junk-removal-brentwood-country-mart.jpg",
    "width": 1600,
    "height": 900,
    "alt": "The red barn-style Brentwood Country Mart on 26th Street in Brentwood, Los Angeles",
    "title": "The Brentwood Country Mart — Junk Removal in Brentwood, CA | Dump Happy",
    "caption": "The Brentwood Country Mart, Brentwood",
    "lat": 34.0467,
    "lon": -118.4948,
    "credit": {
      "author": "Mx. Granger",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brentwood_Country_Mart_2.jpg",
      "attributionRequired": false
    }
  },
  "westchester": {
    "slug": "westchester",
    "src": "/locations/westchester-junk-removal-sepulveda-boulevard.jpg",
    "width": 1600,
    "height": 900,
    "alt": "View over the Westchester neighborhood and Sepulveda Boulevard shopping district near LAX, Los Angeles",
    "title": "Westchester along Sepulveda Boulevard — Junk Removal in Westchester, CA | Dump Happy",
    "caption": "Westchester along Sepulveda Boulevard, Westchester",
    "lat": 33.959,
    "lon": -118.396,
    "credit": {
      "author": "Bill Abbott",
      "license": "CC BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:0745_Westchester_shopping_district_along_Sepulveda_Blvd_North_of_LAX_DSC_0745_(49104179326).jpg",
      "attributionRequired": true
    }
  },
  "mid-city": {
    "slug": "mid-city",
    "src": "/locations/mid-city-junk-removal-mid-city-sign.jpg",
    "width": 1600,
    "height": 900,
    "alt": "City of Los Angeles Mid City neighborhood sign near La Brea Avenue, Mid-City Los Angeles",
    "title": "The Mid-City neighborhood sign — Junk Removal in Mid-City, CA | Dump Happy",
    "caption": "The Mid-City neighborhood sign, Mid-City",
    "lat": 34.0355,
    "lon": -118.3445,
    "credit": {
      "author": "Phatblackmama",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mid-Citysignage1.jpg",
      "attributionRequired": true
    }
  },
  "koreatown": {
    "slug": "koreatown",
    "src": "/locations/koreatown-junk-removal-embassy-apartments.jpg",
    "width": 1600,
    "height": 900,
    "alt": "Historic Embassy Apartments building with its rooftop sign on Mariposa Avenue in Koreatown, Los Angeles",
    "title": "The Embassy Apartments on Mariposa Avenue — Junk Removal in Koreatown, CA | Dump Happy",
    "caption": "The Embassy Apartments on Mariposa Avenue, Koreatown",
    "lat": 34.06,
    "lon": -118.2995,
    "credit": {
      "author": "Downtowngal",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Embassy_Apartments_roof_sign,_Koreatown_Los_Angeles.jpg",
      "attributionRequired": true
    }
  }
};

export function getLocationPhoto(slug: string): LocationPhoto | undefined {
  return LOCATION_PHOTOS[slug];
}
